name:                llvm-lambda
version:             0.1.0.0
github:              "tyehle/llvm-lambda"
license:             BSD3
author:              "Tobin Yehle"
maintainer:          "tobinyehle@gmail.com"
copyright:           "2018 Tobin Yehle"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/tyehle/llvm-lambda#readme>

dependencies:
- base
- bytestring
- containers
- directory
- filepath
- llvm-hs
#- llvm-hs-pretty
- llvm-hs-pure
- megaparsec
- mtl
- optparse-applicative
- process
- text
- transformers
- utf8-string

library:
  source-dirs: src
  dependencies: []

executables:
  tlc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-deprecations
    dependencies:
    - llvm-lambda

tests:
  llvm-lambda-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - llvm-lambda
    - regex-pcre-builtin
    - tasty
    - tasty-hunit
    - tasty-golden
    - raw-strings-qq
    - utf8-string
