name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Packages
      run: |
        # get system packages
        set -euxo pipefail
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get update -q
        sudo apt-get install -yq llvm-15-dev clang-15
        # make sure we have llvm binaries on the path
        echo "/usr/lib/llvm-15/bin" >> $GITHUB_PATH

        # install just
        sudo snap install --edge --classic just

    - name: Verify package install
      run: |
        set -euxo pipefail
        ls -la $(which llvm-config-15)
        llvm-config --version
        clang --version

    - name: Cache Global Stack
      uses: actions/cache@v1
      with:
        path: ~/.stack/
        key: stack-global-${{ hashFiles('package.yaml') }}-${{ hashFiles('stack.yaml') }}
        restore-keys: stack-global

    - name: Install Dependencies
      run: just install-dev-deps

    - name: Build
      run: just build

    - name: Test
      run: just test
